### ISSUE TITLE
INtegration stopped working

### ISSUE THREAD

**Issue by Johans1972** [brianrobertjames/Home-Assistant#6]
### had this integration working well with 2 fitbit accounts.
And when i updated to homeassistant version 2023.3 it stopped working.
I get this error message in logfile.

Logger: homeassistant.components.sensor
Source: custom_components/fitbit1/sensor.py:197
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 01:58:08 (1 occurrences)
Last logged: 01:58:08

Error while setting up fitbit1 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fitbit1/sensor.py", line 197, in setup_platform
    authd_client.client.refresh_token()
  File "/usr/local/lib/python3.10/site-packages/fitbit/api.py", line 156, in refresh_token
    token = self.session.refresh_token(
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant)

**Comment by satyambaba** [comment]
@TheTroubleshooter, can you please update the integration whenever you have time? I checked the code for the official HA integration and noticed that it has changed. I made the appropriate changes by referencing your files, however it is not working. I believe I am missing something in the sensor.py file. I am attaching the files that I edited. Thanks a lot for your efforts.

[fitbit2_edited_code.zip](https://github.com/TheTroubleshooter/Home-Assistant/files/12417501/fitbit2_edited_code.zip)
